# Generated by Django 5.2.4 on 2025-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('date_issued', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
